name       : gnome-mime-data
version    : 2.18.0
release    : 2
source     :
    - https://download.gnome.org/sources/gnome-mime-data/2.18/gnome-mime-data-2.18.0.tar.gz : 86638a38d5e1d05687ee36ddfecab106dc127b120194a55aca0d3ed289a21037
license    : GPL-2.0-or-later
component  : programming.library
summary    : Gnome Mime Data
description: |
    This module contains the base MIME and Application database for GNOME. It is meant to be accessed through the MIME functions in GnomeVFS.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
